### PR TITLE
Make user flows persistent

### PR DESCRIPTION
**Pull request by TechplexEngineer**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Without having the VOLUME statement user flows do not persist. Further, when following the guide here https://nodered.org/docs/platforms/docker and attempting to map the /data directory to a host directory the settings.js, lib and package.json are lost with the suggested command: `docker run -it -p 1880:1880 -v ~/node-red-data:/data --name mynodered nodered/node-red-docker`

Alternatively allowing docker to select the volume location with this syntax does not clear the /data directory:
```
docker run -d \
--name nodered \
--restart always \
-p 1880:1880 \
-v node-red_data:/data \
nodered/node-red-docker
```

Note using docker version:
```
$ docker --version
Docker version 18.06.1-ce, build e68fc7a
```

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [n/a] I have run `grunt` to verify the unit tests pass
- [n/a] I have added suitable unit tests to cover the new/changed functionality

Error message in full:
```
$ docker run -it -p 1880:1880 -v ~/node-red-data:/data --name mynodered nodered/node-red-docker

> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"

fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/data/settings.js'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at copyFileFallback (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:93:18)
    at copyFile (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:85:10)
    at onFile (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:58:12)
    at getStats (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:51:39)
    at startCopy (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:41:10)
    at Object.copySync (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:36:10)
    at Object.<anonymous> (/usr/src/node-red/node_modules/node-red/red.js:104:20)
    at Module._compile (module.js:577:32)

npm ERR! Linux 4.4.0-131-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.0 start script 'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-docker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-docker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-red-docker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/node-red/npm-debug.log
```

### CODE REVIEW

**Comment by thomasleveil** [comment]
isn't this the same as #49 ?

**Comment by mosn** [comment]
Is this repository still being maintained?  I see so many questions floating around and am having somehow a similar issue. Documentations also does nothing to make it better.

**Comment by knolleary** [comment]
It is still maintained. Unfortunately the person with lots of docker experience who was looking after it isn't around to help so some things take a bit more time to resolve whilst we're focused more on the core Node-RED project.

We're aware this isn't a good situation and we'll be looking to improve it in the near future.

**Comment by thomasleveil** [comment]
@knolleary this change is very safe to merge

**Comment by knolleary** [comment]
What documentation updates need to be made to go along with this change?

The current README tells users how to use `-v` to mount a local directory as `/data` in the container. That means the data gets persisted.

From my reading of the docker docs, adding the `volume` declaration to the Dockerfile allows the user to define their own docker volumes and mount them to the container.

**Comment by TechplexEngineer** [comment]
Without the VOLUME statement in the dockerfile the, the user MUST add a -v or their flows will not be persisted.

By simply adding the volume statement docker will create a persistent directory in /var/lib/docker/volumes automatically.

Simply by adding the VOLUME statement the default of 'Flows not persisted' is changed to 'flows automatically persisted'.

**Comment by knolleary** [comment]
It would be great if this PR included suitable updates to the README as well.

**Comment by TechplexEngineer** [comment]
No changes are needed for the readme. it already has sufficient explanation of docker volumes. But this small change is needed to ensure users don't lose their work. Please consider merging before more work is lost (like I did).

**Comment by RaymondMouthaan** [comment]
covered by #124

**Comment by RaymondMouthaan** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.

**Pull request closed without merging**
