### PR TITLE
Added Docker node-red admin command access

### PR DESCRIPTION
**Pull request by MaxVRAM**
Just a documentation addition and slight formatting adjustments for clarity.

- [x ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by MaxVRAM** [comment]
Solving #193

**Comment by dceejay** [comment]
thanks - looking at the README there is already a section around line 372 about node red admin... which is probably where this should fit. Th intention of that section was installing node-red-admin outside of the container and updating the shared volume - but would be useful if it also covered doing it inside the container as you want.

**Comment by MaxVRAM** [comment]
@dceejay I see. I don't think I saw that section when I was first going through the docs. Either way, you're right, there's still a use-case for this. I've popped it under the existing admin section and fixed formatting/wording to be more consistent with the context.

**Comment by dceejay** [comment]
great - many thanks

**Pull request merged**
