### PR TITLE
fix NODE_OPTIONS

### PR DESCRIPTION
**Pull request by twocolors**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by hardillb** [comment]
Thanks for this, but as mentioned in the [contribution guide](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) we can't accept it without a signed CLA. Otherwise I can make the change and close the PR.

I know this is a relatively trivial change, but it also helps to include even a tiny description in the PR.

**Comment by twocolors** [comment]
hmm, ok i logged in. What should happen, resend PR?

**Comment by hardillb** [comment]
Assuming the commit is signed by a public email address attached to your github account then it should verify.

https://docs.linuxfoundation.org/v2/easycla/getting-started/easycla-troubleshooting#github-unable-to-contribute-to-easycla-enforced-repositories

**Comment by twocolors** [comment]
Oh, i have verify email and make commit from web .

**Comment by Steve-Mcl** [comment]
> Oh, i have verify email and make commit from web .

Hi @twocolors, did you actually click the link to sign the CLA?...

[Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/19401550/63426680/333/#/?version=2).

**Comment by twocolors** [comment]
@Steve-Mcl yep , my profile https://openprofile.dev/profile/twocolors

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl yep , my profile https://openprofile.dev/profile/twocolors

I don't believe that is the same thing. 

Can you try again please...

[Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/19401550/63426680/333/#/?version=2).

**Comment by hardillb** [comment]
Since we are having problems getting this signed off via easyCLA I'll apply it from a PR from my account with a note that @twocolors provided the fix.

**Pull request closed without merging**
