### PR TITLE
updates rpi docker image to use official arm32v7 node v10 image

### PR DESCRIPTION
**Pull request by petong**
This is my first PR, hopefully I am doing this right. The changes to the rpi Dockerfile use the official arm32v7 node 10 docker image.

I included changes to let the images build on travis. 

- [X ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ X] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by petong** [comment]
I see the issue is building the docker image since it is targeting the armhf and travis is using ubuntu x86_64.

**Comment by knolleary** [comment]
A broader design discussion needs to happen about the pi docker images. Particularly given the work @raymondmouthaan has done with qemu and the build automation he's got working.

You've changed the default node version - any change like that needs to be done consistently across all of the images we produce.

I'm just getting back from vacation, so may be a few days before we can make progress.in this.

**Comment by petong** [comment]
no worries. I notices there were v10 images for all the other platforms, except raspberry pi, which is what led me down this path. I tested the image with my current running config, then tested building on an ubuntu host.

**Comment by RaymondMouthaan** [comment]
@petong have you looked at my repo [here](https://github.com/RaymondMouthaan/node-red-docker) and [here](https://cloud.docker.com/u/raymondmm/repository/docker/raymondmm/node-red) ?

I am running node-red with node v10 for several months now, without issues on raspberry pi's ;-)

**Comment by petong** [comment]
@RaymondMouthaan I have not! thanks for pointing me in the right direction :) I just installed node-red less than a week ago, so I  am new to the community.

**Comment by petong** [comment]
looks like you have it covered, I'll close the PR. Thanks!

**Comment by RaymondMouthaan** [comment]
@petong, I guess I have. It's like @knolleary said, it's up to the node-red team of making decisions and take things from my repo to build future images for node-red 👌🏽

**Comment by timdonovanuk** [comment]
@RaymondMouthaan do you have a working link for https://cloud.docker.com/u/raymondmm/repository/docker/raymondmm/node-red? There is still no official NR with node v10 docker image.

**Comment by knolleary** [comment]
@timdonovanuk there are node v10 images - https://github.com/node-red/node-red-docker#images. I realise now the docs on nodered.org are out of date and need updating.

**Comment by timdonovanuk** [comment]
@knolleary Sorry, I should have clarified - this thread is about Raspbery Pi's.  There is no v10 listed here https://hub.docker.com/r/nodered/node-red-docker/tags or at your link (in fact your link categorically states there aren't any).

**Comment by petong** [comment]
This is such a simple change and i’ve been running on this PR for a while now, i’m not sure what the delay is getting node 10 oi images going

**Comment by RaymondMouthaan** [comment]
This issue is covered by #124

**Comment by dceejay** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red. 

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.

**Pull request closed without merging**
