### PR TITLE
Enable run on PR

### PR DESCRIPTION
**Pull request by hardillb**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

Enables builds against PRs

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
will this actually create a new build on dockerhub for every PR ? or just do a local build ?

**Comment by hardillb** [comment]
Just a local build, but just fixing it to not even try to log into Docker

**Comment by dceejay** [comment]
ok - - all good then... merge away.

**Comment by knolleary** [comment]
One of the reasons we have to minimise the number of builds we run is we routinely hit the dockerhub pull limits causing builds to fail. That's why we stopped running builds on every PR with Travis.

**Comment by knolleary** [comment]
I know with GH Actions you can have a manual request button. I don't know if its possible to do that per-PR - so builds can be run at request, rather than automatically.

**Comment by hardillb** [comment]
OK, good point. I already have the manual trigger in so I'll re jig this

**Pull request merged**
