### PR TITLE
🚀 Update to Node-RED 2.0.0 release

### PR DESCRIPTION
**Pull request by NodeREDBot**
Updates the Node-RED Docker repo for the 2.0.0 release.

Once this is merged, you will need to create a new release with the tag `v2.0.0`.

This PR was auto-generated by a GitHub Action. Any questions, speak to @knolleary

### CODE REVIEW

**Comment by hardillb** [comment]
This will want the NodeJS v10 stuff manually removing

**Comment by knolleary** [comment]
> This will want the NodeJS v10 stuff manually removing

yeah - the bot just does a global search/replace based on master.

We can close without merging and update manually with the 2.0 changes in place.

**Comment by hardillb** [comment]
I've made the changes in #246 if you want to double check them before I merge and kick off the docker builds

**Comment by hardillb** [comment]
OK, tagging the v2.0.0 build now to kick off the build

**Pull request closed without merging**
