### PR TITLE
Update prep for 4.0.0 beta

### PR DESCRIPTION
**Pull request by hardillb**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

- Update NodeJS versions for 4.0.0
- Update README.md
- Make healthcheck match across all builds
- Update GH Action versions

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Node 22 isn't due until April 2024 - I would hope we have Node-RED 4 beta available long before that. Does it need removing from this PR for now? We can always add 22 later once it is available.

**Comment by hardillb** [comment]
Yep, I'll update the base branch

**Comment by hardillb** [comment]
@knolleary should be good now

**Comment by hardillb** [comment]
Merging

**Pull request merged**
