### PR TITLE
Switch rpi base image to arm32v7/node

### PR DESCRIPTION
**Pull request by sttts**
- Move from deprecated hypriot/rpi-node image to arm32v7/node.
- Build image with real arm architecture (the old image still had amd64 set although it had arm binaries.

### CODE REVIEW

**Comment by knolleary** [comment]
Hi, thanks for this.
Unfortunately you've not used the pull request template we provide that says:

> Please read our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) before submitting a pull-request.

> If you want to raise a pull-request with a new feature, or a refactoring of existing code, it **may well get rejected** if it hasn't been discussed on the [forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack) first.

Had you raised this to discuss, we would have pointed you at 

 - This existing PR https://github.com/node-red/node-red-docker/pull/96
 - This discussion on the forum https://discourse.nodered.org/t/updates-to-docker-images/7502

**Comment by sttts** [comment]
> Had you raised this to discuss, we would have pointed you at

Do those image have the right architecture set? The old ones didn't and docker-stack refused to use them.

**Comment by knolleary** [comment]
No - but there is an active discussion we're just kicking off around a general update across all of the docker images. Please contribute to the discussion because it is more than just updating the base image to consider.

**Comment by sttts** [comment]
Duplicated of https://github.com/node-red/node-red-docker/pull/96, closing.

**Pull request closed without merging**
